name: Update Lure Weights (monthly)

on:
  workflow_dispatch:

jobs:
  call-update-weights:
    runs-on: ubuntu-latest
    steps:
      - name: Mask secrets in logs
        run: |
          echo "::add-mask::${{ secrets.CRON_SECRET }}"
          echo "::add-mask::${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"

      - name: Call Supabase Edge Function
        run: |
          echo "Calling update-weights ..."
          curl -sS -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"name":"Actions"}' \
            "${{ secrets.SUPABASE_URL }}/functions/v1/update-weights"
